version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mysqldb
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_PORT:3306"
    volumes:
      - ./data:/var/lib/mysql
